/*
 * polycall_event.c
 * Implementation for polycall_event.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/polycall_event.h"

/* TODO: Implement functions declared in header */
