# Sinphasé Violation Rules Configuration
violation_detection:
  severity_thresholds:
    warning: 1.0
    critical: 1.5
    emergency: 2.0
  
  isolation_rules:
    tier1_critical_threshold: 1.5
    tier2_moderate_threshold: 1.2
