/*
 * polycall_auth_token.c
 * Implementation for polycall_auth_token.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/auth/polycall_auth_token.h"

/* TODO: Implement functions declared in header */
