/*
 * polycallfile_ignore.c
 * Implementation for polycallfile_ignore.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycallfile/ignore/polycallfile_ignore.h"

/* TODO: Implement functions declared in header */
