/*
 * macro_expander.c
 * Implementation for macro_expander.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycallfile/macro_expander.h"

/* TODO: Implement functions declared in header */
