/*
 * communication.c
 * Implementation for communication.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/protocol/communication.h"

/* TODO: Implement functions declared in header */
