/*
 * network_event.c
 * Implementation for network_event.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/network/network_event.h"

/* TODO: Implement functions declared in header */
