/*
 * network_packet.c
 * Implementation for network_packet.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/network/network_packet.h"

/* TODO: Implement functions declared in header */
