/*
 * network_endpoint.c
 * Implementation for network_endpoint.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/network/network_endpoint.h"

/* TODO: Implement functions declared in header */
