/*
 * network_internal.c
 * Implementation for network_internal.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/network/network_internal.h"

/* TODO: Implement functions declared in header */
