/*
 * main_ioc.c
 * PolyCall CLI Main Driver with IoC
 * Auto-generated by OBINexus Migration Enforcer
 */

#include "command_registry_ioc.h"
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <command> [args...]\n", argv[0]);
    fprintf(stderr, "Use '%s help' for available commands\n", argv[0]);
    return 1;
  }

  // Create IoC registry
  polycall_registry_t *registry = polycall_registry_create();
  if (!registry) {
    fprintf(stderr, "Failed to create command registry\n");
    return 1;
  }

  // Register all command modules
  polycall_register_micro_commands(registry);
  polycall_register_telemetry_commands(registry);
  polycall_register_edge_commands(registry);
  polycall_register_auth_commands(registry);
  polycall_register_config_commands(registry);
  polycall_register_network_commands(registry);

  // Handle help command
  if (strcmp(argv[1], "help") == 0) {
    polycall_registry_list(registry);
    polycall_registry_destroy(registry);
    return 0;
  }

  // Execute command
  int result = polycall_registry_execute(registry, argv[1], argc - 2, argv + 2);

  // Cleanup
  polycall_registry_destroy(registry);
  return result;
}
