# CUSTOM BINDING CONFIGURATION
# Generated: 2025-06-17T21:07:41+01:00
# Domain: banking
# Compliance Level: maximum

[metadata]
binding_name = "jpmorgan-pythonpolycall-banking"
base_language = "python"
domain = "banking"
organization = "jpmorgan"
compliance_level = "maximum"
sinphase_version = "2.0.0"

[inheritance]
base_binding = "pypolycall-secure"
zero_trust_required = true
sinphase_governance = true
telemetry_mandatory = true

[domain_specific]
encryption_standard = "FIPS-140-2-Level-3"
audit_retention_years = 7
transaction_logging = "immutable"
pci_compliance = true
sox_compliance = true
data_residency_required = true
real_time_fraud_detection = true

[security_overrides]
crypto_mode = "quantum-resistant"
identity_verification = true
multi_factor_required = true
biometric_validation = true
session_timeout_minutes = 5
token_rotation_hours = 1
certificate_pinning = true
perfect_forward_secrecy = true
air_gap_protocols = true
hardware_security_module = true

[compliance_requirements]
# Compliance Requirements for banking domain at maximum level
audit_logging = true
telemetry_encryption = true
data_retention_policy = "domain_specific"
privacy_controls = true
incident_response_automation = true
compliance_reporting = "regulatory_standard"
vulnerability_scanning = "continuous"
penetration_testing = "quarterly"

[deployment_targets]
development = "configs/development/banking/"
staging = "configs/staging/banking/"
production = "configs/production/banking/"
