/*
 * compute_router.c
 * Implementation for compute_router.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/edge/compute_router.h"

/* TODO: Implement functions declared in header */
