-- Self-test for frame.lua: pure byte-packing, no sockets needed.
-- Run: lua5.4 frame_test.lua [reference-bytes-file]
--
-- With an argument, also compares frame.encode's output byte-for-byte
-- against a reference frame generated by an already-verified client (see
-- docs/TODO.md P2 -- this is how the Lua framing logic was checked without
-- a live socket: no luasocket is installed here, see docs/backward_compatibility.md).

local frame = require("frame")

local fails = 0
local function check(cond, label)
  if cond then
    print("PASS  " .. label)
  else
    print("FAIL  " .. label)
    fails = fails + 1
  end
end

-- 1. round trip
local payload = '{"action":"describe"}'
local bytes = frame.encode(frame.TYPE_CONTROL, 1, payload)
check(#bytes == frame.HEADER_LEN + #payload, "encoded length = header + payload")

local hdr = bytes:sub(1, frame.HEADER_LEN)
local ftype, corr, length = frame.decode_header(hdr)
check(ftype == frame.TYPE_CONTROL, "decoded type == CONTROL")
check(corr == 1, "decoded correlation id == 1")
check(length == #payload, "decoded length == payload length")
check(bytes:sub(frame.HEADER_LEN + 1) == payload, "decoded payload matches")

-- 2. exact byte layout (hand-verifiable): magic, type=3, flags=0, rsvd=0,
--    corr=1 (00 00 00 01), length=21 (0x00000015) for the 21-byte literal
local expected_hdr = "PCR1" .. "\3" .. "\0" .. "\0\0" .. "\0\0\0\1" .. "\0\0\0\21"
check(hdr == expected_hdr, "header bytes match the hand-computed layout")

-- 3. cross-language byte comparison, when a reference file is given
local ref_path = arg[1]
if ref_path then
  local f = io.open(ref_path, "rb")
  if f then
    local ref = f:read("a")
    f:close()
    check(bytes == ref, "bytes match the reference frame from another client (" .. ref_path .. ")")
  else
    print("NOT RUN  cross-language byte comparison (cannot open " .. ref_path .. ")")
  end
else
  print("NOT RUN  cross-language byte comparison (no reference file given)")
end

print(string.format("--- frame: %d checks, %d failed ---", 6, fails))
os.exit(fails == 0 and 0 or 1)
