/*
 * polycall_protocol_context.c
 * Implementation for polycall_protocol_context.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/protocol/polycall_protocol_context.h"

/* TODO: Implement functions declared in header */
