/*
 * global_config.c
 * Implementation for global_config.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycallfile/global_config.h"

/* TODO: Implement functions declared in header */
