/*
 * hierarchical_state.c
 * Implementation for hierarchical_state.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/hierarchical_state.h"

/* TODO: Implement functions declared in header */
