/*
 * network_client.c
 * Implementation for network_client.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/network/network_client.h"

/* TODO: Implement functions declared in header */
