/*
 * subscription.c
 * Implementation for subscription.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/network/subscription.h"

/* TODO: Implement functions declared in header */
