/*
 * polycall_memory.c
 * Implementation for polycall_memory.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/polycall_memory.h"

/* TODO: Implement functions declared in header */
