/*
 * polycall_state_machine.c
 * Implementation for polycall_state_machine.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/polycall_state_machine.h"

/* TODO: Implement functions declared in header */
