/*
 * edge_component.c
 * Implementation for edge_component.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/edge/edge_component.h"

/* TODO: Implement functions declared in header */
