/*
 * polycall_edge.c
 * Implementation for polycall_edge.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/edge/polycall_edge.h"

/* TODO: Implement functions declared in header */
