# Development Environment Configuration
environment: development
governance:
  base_threshold: 0.8
  fail_on_violations: false
  isolation_enabled: false

reporting:
  level: "summary"
  format: "console"
  fast_feedback: true
