/*
 * protocol_config.c
 * Implementation for protocol_config.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/protocol/protocol_config.h"

/* TODO: Implement functions declared in header */
