/*
 * accessibility_interface.c
 * Implementation for accessibility_interface.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/accessibility/accessibility_interface.h"

/* TODO: Implement functions declared in header */
