/*
 * polycall_error.c
 * Implementation for polycall_error.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/polycall_error.h"

/* TODO: Implement functions declared in header */
