/*
 * language_bridge.c
 * Implementation for language_bridge.h
 * Module: ffi
 * Generated by OBINexus Migration Enforcer
 */

#include "polycall/core/ffi/language_bridge.h"
#include <stdlib.h>
#include <string.h>

