/*
 * polycall_permission.c
 * Implementation for polycall_permission.h
 * Module: polycall
 * Generated by OBINexus Migration Enforcer
 */

#include "polycall/core/polycall/polycall_permission.h"
#include <stdlib.h>
#include <string.h>

