/*
 * polycall_auth_identity.c
 * Implementation for polycall_auth_identity.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/auth/polycall_auth_identity.h"

/* TODO: Implement functions declared in header */
