/*
 * polycall_auth_context.c
 * Implementation for polycall_auth_context.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/auth/polycall_auth_context.h"

/* TODO: Implement functions declared in header */
