/*
 * accessibility_config.c
 * Implementation for accessibility_config.h
 * Auto-generated by violation fixer
 */

#include "polycall/polycall_config.h"

/* TODO: Implement functions declared in header */
