/*
 * language_bridge.c
 * Implementation for language_bridge.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/ffi/language_bridge.h"

/* TODO: Implement functions declared in header */
