/*
 * protocol_bridge.c
 * Implementation for protocol_bridge.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/ffi/protocol_bridge.h"

/* TODO: Implement functions declared in header */
