/*
 * config_parser.c
 * Implementation for config_parser.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/parser/config_parser.h"

/* TODO: Implement functions declared in header */
