/*
 * polycallrc_ignore.c
 * Implementation for polycallrc_ignore.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycallrc/ignore/polycallrc_ignore.h"

/* TODO: Implement functions declared in header */
