#include "polycall/polycall/polycall.h"
/*
 * polycall.c
 * Implementation for polycall.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/polycall.h"

/* TODO: Implement functions declared in header */
