/*
 * polycall_core.c
 * Implementation for polycall_core.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/polycall/polycall_core.h"

/* TODO: Implement functions declared in header */
