/*
 * polycall_ignore.c
 * Implementation for polycall_ignore.h
 * Auto-generated by violation fixer
 */

#include "polycall/core/ignore/polycall_ignore.h"

/* TODO: Implement functions declared in header */
