environment: production
governance:
  base_threshold: 0.6
  autonomous_limit: 0.4
  fail_on_violations: true
  isolation_enabled: true
  emergency_threshold: 1.5
  
reporting:
  level: "comprehensive"
  format: "formal"
  audit_trail: true
  
features:
  compliance_validation: true
  security_assessment: true
  deployment_gates: true
