environment: test
governance:
  base_threshold: 0.7
  autonomous_limit: 0.5
  fail_on_violations: false
  isolation_enabled: false
  
reporting:
  level: "detailed"
  format: "json"
  include_metrics: true
  
features:
  test_coverage_integration: true
  regression_detection: true
  performance_benchmarking: true
